version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    user: "$UID:$GID"
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - ../data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  prometheus-pushgateway:
    image: prom/pushgateway:v1.6.0
    container_name: prometheus-pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    user: "$UID:$GID"
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ../data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
