name: YDB Hibernate Dialect CI with Maven

on:
  push:
    paths:
      - 'hibernate-dialect/**'
    branches:
      - main
  pull_request:
    paths:
      - 'hibernate-dialect/**'
    types:
      - opened
      - reopened
      - edited

env:
  MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

jobs:
  build:
    name: YDB Java Hibernate Dialect
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          cache: maven

      - name: Run tests with Maven
        run: |
          cd hibernate-dialect
          mvn $MAVEN_ARGS test
